version: '3'
services:
  protractor:
    container_name: ccd-case-management-protractor
    image: ccd-protractor:latest
    build:
      context: ./test
      dockerfile: DockerfileTests
    environment:
      - CCD_CASEWORKER_AUTOTEST_FE_EMAIL
      - CCD_CASEWORKER_AUTOTEST_FE_PASSWORD
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - TEST_URL
    volumes:
      - "$PWD:/protractor"
