export type FieldTypeEnum =
  'Text'
  | 'TextArea'
  | 'Postcode'
  | 'Number'
  | 'YesOrNo'
  | 'Date'
  | 'Email'
  | 'PhoneUK'
  | 'MoneyGBP'
  | 'FixedList'
  | 'Complex'
  | 'Collection'
  | 'MultiSelectList'
  | 'Document'
  | 'Label'
  | 'AddressGlobal'
  | 'AddressGlobalUK'
  | 'AddressUK'
  | 'OrderSummary';
