idam_authentication_web_url = "https://idam-web-public.demo.platform.hmcts.net/"
ccd_gateway_url = "https://gateway-ccd.demo.platform.hmcts.net"
document_management_url = "^https?://(?:api-gateway\\.preprod\\.dm\\.reform\\.hmcts\\.net|dm-store-demo\\.service\\.core-compute-demo\\.internal(?::\\d+)?)"
ccd_print_service_url = "http://return-case-doc.ccd.demo.platform.hmcts.net"
activity_enabled = "true"
external_host_name = "www-ccd.demo.platform.hmcts.net"
capacity = "2"
