idam_authentication_web_url = "https://www.idam.reform.hmcts.net"
ccd_gateway_url = "https://gateway.ccd.platform.hmcts.net"
document_management_url = "^https?://(?:api-gateway\\.dm\\.reform\\.hmcts\\.net|dm-store-prod\\.service\\.core-compute-prod\\.internal(?::\\d+)?)"
ccd_print_service_url = "https://return-case-doc.ccd.platform.hmcts.net"
probate_template_url = "http://betaPreProdprobateApp01.reform.hmcts.net:4104"
